---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: kube-helloweb
  annotations:
    fluxcd.io/automated: "true"
    fluxcd.io/tag.helloweb-app: glob:master-*
spec:
  selector:
    matchLabels:
      app: helloweb-app
  replicas: 2
  template:
    metadata:
      labels:
        app: helloweb-app
    spec:
      containers:
      - name: helloweb-app
        image: grahamh/hello-docker-web:2.0
        ports:
        - containerPort: 8080

