---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: kube-helloweb
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.helloweb-app: glob:3*
spec:
  selector:
    matchLabels:
      app: helloweb-app
  replicas: 2
  template:
    metadata:
      labels:
        app: helloweb-app
    spec:
      containers:
      - name: helloweb-app
        image: grahamh/hello-docker-web:4.0
        ports:
        - containerPort: 8080

