---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: nginx-controller
  namespace: stg
  annotations:
    flux.weave.works/automated: "false"
    flux.weave.works/tag.nginx: semver:~1.16
spec:
  releaseName: nginx-controller
  chart:
    git: git@github.com:helm/charts.git
    path: stable/nginx-controller
    ref: master
